//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSoap")]
    internal interface ServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroup", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.getgroupResponse> getgroupAsync(ServiceReference1.getgroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroupForPhoneBook", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.getgroupForPhoneBookResponse> getgroupForPhoneBookAsync(ServiceReference1.getgroupForPhoneBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getmobilebulk", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.getmobilebulkResponse> getmobilebulkAsync(ServiceReference1.getmobilebulkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroupstr", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.getgroupstrResponse> getgroupstrAsync(ServiceReference1.getgroupstrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroupmobiles", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.getgroupmobilesResponse> getgroupmobilesAsync(ServiceReference1.getgroupmobilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroupmobilesstr", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.getgroupmobilesstrResponse> getgroupmobilesstrAsync(ServiceReference1.getgroupmobilesstrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroupcount", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.getgroupcountResponse> getgroupcountAsync(ServiceReference1.getgroupcountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.SendSMSResponse> SendSMSAsync(ServiceReference1.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSWithTime", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.SendSMSWithTimeResponse> SendSMSWithTimeAsync(ServiceReference1.SendSMSWithTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemainSms", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.RemainSmsResponse> RemainSmsAsync(ServiceReference1.RemainSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send1sms", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.Send1smsResponse> Send1smsAsync(ServiceReference1.Send1smsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send1Bulk", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.Send1BulkResponse> Send1BulkAsync(ServiceReference1.Send1BulkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getcitymobiles", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.getcitymobilesResponse> getcitymobilesAsync(ServiceReference1.getcitymobilesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getgroupRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroup", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.getgroupRequestBody Body;
        
        public getgroupRequest()
        {
        }
        
        public getgroupRequest(ServiceReference1.getgroupRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class getgroupRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appcode;
        
        public getgroupRequestBody()
        {
        }
        
        public getgroupRequestBody(string appcode)
        {
            this.appcode = appcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getgroupResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.getgroupResponseBody Body;
        
        public getgroupResponse()
        {
        }
        
        public getgroupResponse(ServiceReference1.getgroupResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class getgroupResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getgroupResult;
        
        public getgroupResponseBody()
        {
        }
        
        public getgroupResponseBody(string getgroupResult)
        {
            this.getgroupResult = getgroupResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getgroupForPhoneBookRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupForPhoneBook", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.getgroupForPhoneBookRequestBody Body;
        
        public getgroupForPhoneBookRequest()
        {
        }
        
        public getgroupForPhoneBookRequest(ServiceReference1.getgroupForPhoneBookRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class getgroupForPhoneBookRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public getgroupForPhoneBookRequestBody()
        {
        }
        
        public getgroupForPhoneBookRequestBody(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getgroupForPhoneBookResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupForPhoneBookResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.getgroupForPhoneBookResponseBody Body;
        
        public getgroupForPhoneBookResponse()
        {
        }
        
        public getgroupForPhoneBookResponse(ServiceReference1.getgroupForPhoneBookResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class getgroupForPhoneBookResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getgroupForPhoneBookResult;
        
        public getgroupForPhoneBookResponseBody()
        {
        }
        
        public getgroupForPhoneBookResponseBody(string getgroupForPhoneBookResult)
        {
            this.getgroupForPhoneBookResult = getgroupForPhoneBookResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getmobilebulkRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getmobilebulk", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.getmobilebulkRequestBody Body;
        
        public getmobilebulkRequest()
        {
        }
        
        public getmobilebulkRequest(ServiceReference1.getmobilebulkRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class getmobilebulkRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string postcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string citycode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mode;
        
        public getmobilebulkRequestBody()
        {
        }
        
        public getmobilebulkRequestBody(string appcode, string postcode, string citycode, string mode)
        {
            this.appcode = appcode;
            this.postcode = postcode;
            this.citycode = citycode;
            this.mode = mode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getmobilebulkResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getmobilebulkResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.getmobilebulkResponseBody Body;
        
        public getmobilebulkResponse()
        {
        }
        
        public getmobilebulkResponse(ServiceReference1.getmobilebulkResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class getmobilebulkResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getmobilebulkResult;
        
        public getmobilebulkResponseBody()
        {
        }
        
        public getmobilebulkResponseBody(string getmobilebulkResult)
        {
            this.getmobilebulkResult = getmobilebulkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getgroupstrRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupstr", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.getgroupstrRequestBody Body;
        
        public getgroupstrRequest()
        {
        }
        
        public getgroupstrRequest(ServiceReference1.getgroupstrRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class getgroupstrRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appcode;
        
        public getgroupstrRequestBody()
        {
        }
        
        public getgroupstrRequestBody(string appcode)
        {
            this.appcode = appcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getgroupstrResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupstrResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.getgroupstrResponseBody Body;
        
        public getgroupstrResponse()
        {
        }
        
        public getgroupstrResponse(ServiceReference1.getgroupstrResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class getgroupstrResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getgroupstrResult;
        
        public getgroupstrResponseBody()
        {
        }
        
        public getgroupstrResponseBody(string getgroupstrResult)
        {
            this.getgroupstrResult = getgroupstrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getgroupmobilesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupmobiles", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.getgroupmobilesRequestBody Body;
        
        public getgroupmobilesRequest()
        {
        }
        
        public getgroupmobilesRequest(ServiceReference1.getgroupmobilesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class getgroupmobilesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string groupid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string appcode;
        
        public getgroupmobilesRequestBody()
        {
        }
        
        public getgroupmobilesRequestBody(string groupid, string appcode)
        {
            this.groupid = groupid;
            this.appcode = appcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getgroupmobilesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupmobilesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.getgroupmobilesResponseBody Body;
        
        public getgroupmobilesResponse()
        {
        }
        
        public getgroupmobilesResponse(ServiceReference1.getgroupmobilesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class getgroupmobilesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getgroupmobilesResult;
        
        public getgroupmobilesResponseBody()
        {
        }
        
        public getgroupmobilesResponseBody(string getgroupmobilesResult)
        {
            this.getgroupmobilesResult = getgroupmobilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getgroupmobilesstrRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupmobilesstr", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.getgroupmobilesstrRequestBody Body;
        
        public getgroupmobilesstrRequest()
        {
        }
        
        public getgroupmobilesstrRequest(ServiceReference1.getgroupmobilesstrRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class getgroupmobilesstrRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string groupid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string appcode;
        
        public getgroupmobilesstrRequestBody()
        {
        }
        
        public getgroupmobilesstrRequestBody(string groupid, string appcode)
        {
            this.groupid = groupid;
            this.appcode = appcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getgroupmobilesstrResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupmobilesstrResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.getgroupmobilesstrResponseBody Body;
        
        public getgroupmobilesstrResponse()
        {
        }
        
        public getgroupmobilesstrResponse(ServiceReference1.getgroupmobilesstrResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class getgroupmobilesstrResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getgroupmobilesstrResult;
        
        public getgroupmobilesstrResponseBody()
        {
        }
        
        public getgroupmobilesstrResponseBody(string getgroupmobilesstrResult)
        {
            this.getgroupmobilesstrResult = getgroupmobilesstrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getgroupcountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupcount", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.getgroupcountRequestBody Body;
        
        public getgroupcountRequest()
        {
        }
        
        public getgroupcountRequest(ServiceReference1.getgroupcountRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class getgroupcountRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string groupid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string appcode;
        
        public getgroupcountRequestBody()
        {
        }
        
        public getgroupcountRequestBody(string groupid, string appcode)
        {
            this.groupid = groupid;
            this.appcode = appcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getgroupcountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupcountResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.getgroupcountResponseBody Body;
        
        public getgroupcountResponse()
        {
        }
        
        public getgroupcountResponse(ServiceReference1.getgroupcountResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class getgroupcountResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getgroupcountResult;
        
        public getgroupcountResponseBody()
        {
        }
        
        public getgroupcountResponseBody(string getgroupcountResult)
        {
            this.getgroupcountResult = getgroupcountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.SendSMSRequestBody Body;
        
        public SendSMSRequest()
        {
        }
        
        public SendSMSRequest(ServiceReference1.SendSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class SendSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mobileno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pnlno;
        
        public SendSMSRequestBody()
        {
        }
        
        public SendSMSRequestBody(string username, string password, string text, string mobileno, string pnlno)
        {
            this.username = username;
            this.password = password;
            this.text = text;
            this.mobileno = mobileno;
            this.pnlno = pnlno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.SendSMSResponseBody Body;
        
        public SendSMSResponse()
        {
        }
        
        public SendSMSResponse(ServiceReference1.SendSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class SendSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMSResult;
        
        public SendSMSResponseBody()
        {
        }
        
        public SendSMSResponseBody(string SendSMSResult)
        {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendSMSWithTimeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSWithTime", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.SendSMSWithTimeRequestBody Body;
        
        public SendSMSWithTimeRequest()
        {
        }
        
        public SendSMSWithTimeRequest(ServiceReference1.SendSMSWithTimeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class SendSMSWithTimeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mobileno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pnlno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Timestmp;
        
        public SendSMSWithTimeRequestBody()
        {
        }
        
        public SendSMSWithTimeRequestBody(string username, string password, string text, string mobileno, string pnlno, string Timestmp)
        {
            this.username = username;
            this.password = password;
            this.text = text;
            this.mobileno = mobileno;
            this.pnlno = pnlno;
            this.Timestmp = Timestmp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendSMSWithTimeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSWithTimeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.SendSMSWithTimeResponseBody Body;
        
        public SendSMSWithTimeResponse()
        {
        }
        
        public SendSMSWithTimeResponse(ServiceReference1.SendSMSWithTimeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class SendSMSWithTimeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMSWithTimeResult;
        
        public SendSMSWithTimeResponseBody()
        {
        }
        
        public SendSMSWithTimeResponseBody(string SendSMSWithTimeResult)
        {
            this.SendSMSWithTimeResult = SendSMSWithTimeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class RemainSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemainSms", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.RemainSmsRequestBody Body;
        
        public RemainSmsRequest()
        {
        }
        
        public RemainSmsRequest(ServiceReference1.RemainSmsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class RemainSmsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public RemainSmsRequestBody()
        {
        }
        
        public RemainSmsRequestBody(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class RemainSmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemainSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.RemainSmsResponseBody Body;
        
        public RemainSmsResponse()
        {
        }
        
        public RemainSmsResponse(ServiceReference1.RemainSmsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class RemainSmsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RemainSmsResult;
        
        public RemainSmsResponseBody()
        {
        }
        
        public RemainSmsResponseBody(string RemainSmsResult)
        {
            this.RemainSmsResult = RemainSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class Send1smsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send1sms", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.Send1smsRequestBody Body;
        
        public Send1smsRequest()
        {
        }
        
        public Send1smsRequest(ServiceReference1.Send1smsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class Send1smsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobileno;
        
        public Send1smsRequestBody()
        {
        }
        
        public Send1smsRequestBody(string username, string text, string mobileno)
        {
            this.username = username;
            this.text = text;
            this.mobileno = mobileno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class Send1smsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send1smsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.Send1smsResponseBody Body;
        
        public Send1smsResponse()
        {
        }
        
        public Send1smsResponse(ServiceReference1.Send1smsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class Send1smsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Send1smsResult;
        
        public Send1smsResponseBody()
        {
        }
        
        public Send1smsResponseBody(string Send1smsResult)
        {
            this.Send1smsResult = Send1smsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class Send1BulkRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send1Bulk", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.Send1BulkRequestBody Body;
        
        public Send1BulkRequest()
        {
        }
        
        public Send1BulkRequest(ServiceReference1.Send1BulkRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class Send1BulkRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobileno;
        
        public Send1BulkRequestBody()
        {
        }
        
        public Send1BulkRequestBody(string username, string text, string mobileno)
        {
            this.username = username;
            this.text = text;
            this.mobileno = mobileno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class Send1BulkResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send1BulkResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.Send1BulkResponseBody Body;
        
        public Send1BulkResponse()
        {
        }
        
        public Send1BulkResponse(ServiceReference1.Send1BulkResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class Send1BulkResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Send1BulkResult;
        
        public Send1BulkResponseBody()
        {
        }
        
        public Send1BulkResponseBody(string Send1BulkResult)
        {
            this.Send1BulkResult = Send1BulkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getcitymobilesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getcitymobiles", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.getcitymobilesRequestBody Body;
        
        public getcitymobilesRequest()
        {
        }
        
        public getcitymobilesRequest(ServiceReference1.getcitymobilesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class getcitymobilesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cityid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int mode;
        
        public getcitymobilesRequestBody()
        {
        }
        
        public getcitymobilesRequestBody(string cityid, int mode)
        {
            this.cityid = cityid;
            this.mode = mode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getcitymobilesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getcitymobilesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.getcitymobilesResponseBody Body;
        
        public getcitymobilesResponse()
        {
        }
        
        public getcitymobilesResponse(ServiceReference1.getcitymobilesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class getcitymobilesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getcitymobilesResult;
        
        public getcitymobilesResponseBody()
        {
        }
        
        public getcitymobilesResponseBody(string getcitymobilesResult)
        {
            this.getcitymobilesResult = getcitymobilesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal interface ServiceSoapChannel : ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal partial class ServiceSoapClient : System.ServiceModel.ClientBase<ServiceReference1.ServiceSoap>, ServiceReference1.ServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getgroupResponse> ServiceReference1.ServiceSoap.getgroupAsync(ServiceReference1.getgroupRequest request)
        {
            return base.Channel.getgroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getgroupResponse> getgroupAsync(string appcode)
        {
            ServiceReference1.getgroupRequest inValue = new ServiceReference1.getgroupRequest();
            inValue.Body = new ServiceReference1.getgroupRequestBody();
            inValue.Body.appcode = appcode;
            return ((ServiceReference1.ServiceSoap)(this)).getgroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getgroupForPhoneBookResponse> ServiceReference1.ServiceSoap.getgroupForPhoneBookAsync(ServiceReference1.getgroupForPhoneBookRequest request)
        {
            return base.Channel.getgroupForPhoneBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getgroupForPhoneBookResponse> getgroupForPhoneBookAsync(string username, string password)
        {
            ServiceReference1.getgroupForPhoneBookRequest inValue = new ServiceReference1.getgroupForPhoneBookRequest();
            inValue.Body = new ServiceReference1.getgroupForPhoneBookRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((ServiceReference1.ServiceSoap)(this)).getgroupForPhoneBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getmobilebulkResponse> ServiceReference1.ServiceSoap.getmobilebulkAsync(ServiceReference1.getmobilebulkRequest request)
        {
            return base.Channel.getmobilebulkAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getmobilebulkResponse> getmobilebulkAsync(string appcode, string postcode, string citycode, string mode)
        {
            ServiceReference1.getmobilebulkRequest inValue = new ServiceReference1.getmobilebulkRequest();
            inValue.Body = new ServiceReference1.getmobilebulkRequestBody();
            inValue.Body.appcode = appcode;
            inValue.Body.postcode = postcode;
            inValue.Body.citycode = citycode;
            inValue.Body.mode = mode;
            return ((ServiceReference1.ServiceSoap)(this)).getmobilebulkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getgroupstrResponse> ServiceReference1.ServiceSoap.getgroupstrAsync(ServiceReference1.getgroupstrRequest request)
        {
            return base.Channel.getgroupstrAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getgroupstrResponse> getgroupstrAsync(string appcode)
        {
            ServiceReference1.getgroupstrRequest inValue = new ServiceReference1.getgroupstrRequest();
            inValue.Body = new ServiceReference1.getgroupstrRequestBody();
            inValue.Body.appcode = appcode;
            return ((ServiceReference1.ServiceSoap)(this)).getgroupstrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getgroupmobilesResponse> ServiceReference1.ServiceSoap.getgroupmobilesAsync(ServiceReference1.getgroupmobilesRequest request)
        {
            return base.Channel.getgroupmobilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getgroupmobilesResponse> getgroupmobilesAsync(string groupid, string appcode)
        {
            ServiceReference1.getgroupmobilesRequest inValue = new ServiceReference1.getgroupmobilesRequest();
            inValue.Body = new ServiceReference1.getgroupmobilesRequestBody();
            inValue.Body.groupid = groupid;
            inValue.Body.appcode = appcode;
            return ((ServiceReference1.ServiceSoap)(this)).getgroupmobilesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getgroupmobilesstrResponse> ServiceReference1.ServiceSoap.getgroupmobilesstrAsync(ServiceReference1.getgroupmobilesstrRequest request)
        {
            return base.Channel.getgroupmobilesstrAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getgroupmobilesstrResponse> getgroupmobilesstrAsync(string groupid, string appcode)
        {
            ServiceReference1.getgroupmobilesstrRequest inValue = new ServiceReference1.getgroupmobilesstrRequest();
            inValue.Body = new ServiceReference1.getgroupmobilesstrRequestBody();
            inValue.Body.groupid = groupid;
            inValue.Body.appcode = appcode;
            return ((ServiceReference1.ServiceSoap)(this)).getgroupmobilesstrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getgroupcountResponse> ServiceReference1.ServiceSoap.getgroupcountAsync(ServiceReference1.getgroupcountRequest request)
        {
            return base.Channel.getgroupcountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getgroupcountResponse> getgroupcountAsync(string groupid, string appcode)
        {
            ServiceReference1.getgroupcountRequest inValue = new ServiceReference1.getgroupcountRequest();
            inValue.Body = new ServiceReference1.getgroupcountRequestBody();
            inValue.Body.groupid = groupid;
            inValue.Body.appcode = appcode;
            return ((ServiceReference1.ServiceSoap)(this)).getgroupcountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.SendSMSResponse> ServiceReference1.ServiceSoap.SendSMSAsync(ServiceReference1.SendSMSRequest request)
        {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SendSMSResponse> SendSMSAsync(string username, string password, string text, string mobileno, string pnlno)
        {
            ServiceReference1.SendSMSRequest inValue = new ServiceReference1.SendSMSRequest();
            inValue.Body = new ServiceReference1.SendSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.text = text;
            inValue.Body.mobileno = mobileno;
            inValue.Body.pnlno = pnlno;
            return ((ServiceReference1.ServiceSoap)(this)).SendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.SendSMSWithTimeResponse> ServiceReference1.ServiceSoap.SendSMSWithTimeAsync(ServiceReference1.SendSMSWithTimeRequest request)
        {
            return base.Channel.SendSMSWithTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SendSMSWithTimeResponse> SendSMSWithTimeAsync(string username, string password, string text, string mobileno, string pnlno, string Timestmp)
        {
            ServiceReference1.SendSMSWithTimeRequest inValue = new ServiceReference1.SendSMSWithTimeRequest();
            inValue.Body = new ServiceReference1.SendSMSWithTimeRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.text = text;
            inValue.Body.mobileno = mobileno;
            inValue.Body.pnlno = pnlno;
            inValue.Body.Timestmp = Timestmp;
            return ((ServiceReference1.ServiceSoap)(this)).SendSMSWithTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.RemainSmsResponse> ServiceReference1.ServiceSoap.RemainSmsAsync(ServiceReference1.RemainSmsRequest request)
        {
            return base.Channel.RemainSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.RemainSmsResponse> RemainSmsAsync(string username, string password)
        {
            ServiceReference1.RemainSmsRequest inValue = new ServiceReference1.RemainSmsRequest();
            inValue.Body = new ServiceReference1.RemainSmsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((ServiceReference1.ServiceSoap)(this)).RemainSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.Send1smsResponse> ServiceReference1.ServiceSoap.Send1smsAsync(ServiceReference1.Send1smsRequest request)
        {
            return base.Channel.Send1smsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Send1smsResponse> Send1smsAsync(string username, string text, string mobileno)
        {
            ServiceReference1.Send1smsRequest inValue = new ServiceReference1.Send1smsRequest();
            inValue.Body = new ServiceReference1.Send1smsRequestBody();
            inValue.Body.username = username;
            inValue.Body.text = text;
            inValue.Body.mobileno = mobileno;
            return ((ServiceReference1.ServiceSoap)(this)).Send1smsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.Send1BulkResponse> ServiceReference1.ServiceSoap.Send1BulkAsync(ServiceReference1.Send1BulkRequest request)
        {
            return base.Channel.Send1BulkAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Send1BulkResponse> Send1BulkAsync(string username, string text, string mobileno)
        {
            ServiceReference1.Send1BulkRequest inValue = new ServiceReference1.Send1BulkRequest();
            inValue.Body = new ServiceReference1.Send1BulkRequestBody();
            inValue.Body.username = username;
            inValue.Body.text = text;
            inValue.Body.mobileno = mobileno;
            return ((ServiceReference1.ServiceSoap)(this)).Send1BulkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getcitymobilesResponse> ServiceReference1.ServiceSoap.getcitymobilesAsync(ServiceReference1.getcitymobilesRequest request)
        {
            return base.Channel.getcitymobilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getcitymobilesResponse> getcitymobilesAsync(string cityid, int mode)
        {
            ServiceReference1.getcitymobilesRequest inValue = new ServiceReference1.getcitymobilesRequest();
            inValue.Body = new ServiceReference1.getcitymobilesRequestBody();
            inValue.Body.cityid = cityid;
            inValue.Body.mode = mode;
            return ((ServiceReference1.ServiceSoap)(this)).getcitymobilesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://webservice.0098sms.com/service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://webservice.0098sms.com/service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
}
